name: CouchPotato
description: |
  Awesome PVR for usenet and torrents. Just fill in what you want to see and
  CouchPotato will add it to your "want to watch"-list. Every day it will
  search through multiple NZBs & Torrents sites, looking for the best possible
  match.
  If available, it will download it using your favorite download software.
version: "0.1.0"
category: Media
maintainer: Eric Young
license: Apache, v2
projectURL: https://couchpota.to/
