version: '2'
.catalog:
  name: "RaspberryPints"
  version: "0.3.0"
  description: |
    A digital signage version of the common chalkboard-based taplist.
  minimum_rancher_version: v1.1.0
  maximum_rancher_version: v1.99.99
  questions:
    - variable: "EXPOSED_PORT"
      label: Port
      description: "Which port should pints be exposed on?"
      default: 80
      required: true
      type: string
    - variable: "CONFIGDIR"
      label: Config Volume
      description: "Volume on which to store configuration data"
      required: true
      type: string

raspberrypints:
  scale: 1
  retain_ip: true
  health_check:
    port: 80
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
