version: '2'
.catalog:
  name: "Sickrage"
  version: "0.1.0"
  description: |
    Automatic Video Library Manager for TV Shows. It watches for new episodes
    of your favorite shows, and when they are posted it does its magic..
  minimum_rancher_version: v1.1.0
  maximum_rancher_version: v1.99.99
  questions:
    - variable: "EXPOSED_PORT"
      label: Port
      description: "Which port should sickrage listen on?"
      default: 8081
      required: true
      type: string
    - variable: "CONFIGDIR"
      label: Config Volume
      description: "Volume on which to store configuration data"
      required: true
      type: string
    - variable: "VIDEODIR"
      label: Video Volume
      description: "Volume on which to store media"
      required: true
      type: string
    - variable: "DOWNLOADDIR"
      label: Downloads Volume
      description: "Volume where downloads are placed by a downloader"
      required: true
      type: string

sickrage:
  scale: 1
  retain_ip: true
  health_check:
    port: 8081
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
