version: '2'
.catalog:
  name: "CouchPotato"
  version: "0.1.0"
  description: |
    Download movies automatically, easily and in the best quality as
    soon as they are available
  minimum_rancher_version: v1.1.0
  maximum_rancher_version: v1.99.99
  questions:
    - variable: "EXPOSED_PORT"
      label: Port
      description: "Which port should couchpotato listen on?"
      default: 5050
      required: true
      type: string
    - variable: "CONFIGDIR"
      label: Config Volume
      description: "Volume on which to store configuration data"
      required: true
      type: string
    - variable: "VIDEODIR"
      label: Video Volume
      description: "Volume on which to store media"
      required: true
      type: string
    - variable: "DOWNLOADDIR"
      label: Downloads Volume
      description: "Volume where downloads are placed by a downloader"
      required: true
      type: string

couchpotato:
  scale: 1
  retain_ip: true
  health_check:
    port: 5050
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
