name: Mylar
description: |
  An automated Comic Book downloader (cbr/cbz) for use with SABnzbd, NZBGet and torrents.
version: "0.1.0"
category: Media
maintainer: Eric Young
license: Apache, v2
projectURL: https://github.com/evilhero/mylar
