version: '2'
.catalog:
  name: "Mylar"
  version: "0.1.0"
  description: |
    Mylar is an automated Comic Book (cbr/cbz) downloader program heavily-based
    on the Headphones template and logic (which is also based on Sick-Beard).
  minimum_rancher_version: v1.1.0
  maximum_rancher_version: v1.99.99
  questions:
    - variable: "EXPOSED_PORT"
      label: Port
      description: "Which port should sickrage listen on?"
      default: 8090
      required: true
      type: string
    - variable: "CONFIGDIR"
      label: Config Volume
      description: "Volume on which to store configuration data"
      required: true
      type: string
    - variable: "COMICSDIR"
      label: Comics Volume
      description: "Volume on which to store comics"
      required: true
      type: string
    - variable: "DOWNLOADDIR"
      label: Downloads Volume
      description: "Volume where downloads are placed by a downloader"
      required: true
      type: string

mylar:
  scale: 1
  retain_ip: true
  health_check:
    port: 8090
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
